name: Run main.py every Monday

on:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on Monday
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python src/main.py
