name: Run main.py every Monday

on:
  schedule:
    - cron: "0 0 * * 1" # At 00:00 on Monday
  workflow_dispatch:

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main.py
        run: python src/main.py

      - name: Add archive/*.md and stats/*.csv
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add archive/*.md stats/*.csv
          git commit -m "Update markdown reports and stats CSVs [skip ci]" || echo "No changes to commit"
          git push
